pipeline:
  name: deploy
  identifier: deploy
  projectIdentifier: fastfluxdemo
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: CI-Test
        identifier: CITest
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Build_fast_flux_1677808822161
          project: fastfluxdemo
          inputs:
            identifier: Build_fast_flux_1677808822161
            properties:
              ci:
                codebase:
                  build: <+input>
          outputs: []
    - stage:
        name: dev_deploy
        identifier: dev_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: fast_flux
          environment:
            environmentRef: org.Development
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cgmacdev
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
              - step:
                  type: Wait
                  name: Wait_1
                  identifier: Wait_1
                  spec:
                    duration: 1m
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
    - stage:
        name: approve-prod
        identifier: approveprod
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: approve-prod-fast-flux
                  identifier: approveprodfastflux
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
        tags: {}
    - stage:
        name: prod_deploy
        identifier: prod_deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            useFromStage:
              stage: dev_deploy
          environment:
            environmentRef: org.Production
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cgmacprod
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
