pipeline:
  name: merge
  identifier: merge
  projectIdentifier: fastflux
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: ci_test
        identifier: ci_test
        description: ""
        type: Pipeline
        spec:
          org: default
          pipeline: Unit_Test
          project: fastflux
          inputs:
            identifier: Unit_Test
            properties:
              ci:
                codebase:
                  build: <+input>
          outputs: []
    - stage:
        name: deploy_dev
        identifier: deploy_dev
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: Fast_Flux
          environment:
            environmentRef: Dev
            deployToAll: false
            infrastructureDefinitions:
              - identifier: cg_laptop
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    ignoreReleaseHistFailStatus: false
                    delegateSelectors:
                      - cg-mac
                  failureStrategies: []
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: DOCKER_REPO
      type: String
      description: ""
      value: carsongee/fast-flux
